#!/usr/bin/env python3
"""Emit per-species placeholder data for NUM_RESERVED_CUSTOM_SPECIES slots.

Run from repo root (see Makefile). Count must match include/constants/species.h layout:
  SPECIES_EGG == SPECIES_CHIMECHO + 1 + NUM_RESERVED_CUSTOM_SPECIES
"""

from __future__ import annotations

import os
import sys

OUT_DIR = os.path.join("include", "constants", "generated")


def write_if_changed(path: str, text: str) -> None:
    try:
        with open(path, encoding="utf-8") as f:
            if f.read() == text:
                return
    except OSError:
        pass
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def species_id(i: int) -> str:
    return f"(SPECIES_CHIMECHO + 1 + {i})"


def species_info_entry(i: int) -> str:
    sid = species_id(i)
    return f"""    [{sid}] =
    {{
        .baseHP = 40,
        .baseAttack = 45,
        .baseDefense = 40,
        .baseSpeed = 50,
        .baseSpAttack = 40,
        .baseSpDefense = 40,
        .types = {{TYPE_NORMAL, TYPE_NORMAL}},
        .catchRate = 255,
        .expYield = 62,
        .evYield_HP = 0,
        .evYield_Attack = 0,
        .evYield_Defense = 0,
        .evYield_Speed = 0,
        .evYield_SpAttack = 0,
        .evYield_SpDefense = 0,
        .itemCommon = ITEM_NONE,
        .itemRare = ITEM_NONE,
        .genderRatio = PERCENT_FEMALE(50),
        .eggCycles = 20,
        .friendship = 70,
        .growthRate = GROWTH_MEDIUM_FAST,
        .eggGroups = {{EGG_GROUP_FIELD, EGG_GROUP_FIELD}},
        .abilities = {{ABILITY_NONE, ABILITY_NONE}},
        .safariZoneFleeRate = 0,
        .bodyColor = BODY_COLOR_GRAY,
        .noFlip = FALSE,
    }},"""


def main() -> None:
    n = int(sys.argv[1]) if len(sys.argv) > 1 else int(os.environ.get("NUM_RESERVED_CUSTOM_SPECIES", "16"))
    if n < 0 or n > 64:
        print("count must be 0..64", file=sys.stderr)
        sys.exit(1)

    os.makedirs(OUT_DIR, exist_ok=True)

    banner = (
        "/* Auto-generated by tools/gen_reserved_species_tables.py — do not edit. */\n"
        f"/* NUM_RESERVED_CUSTOM_SPECIES = {n} */\n\n"
    )

    # species_info.h
    body = "".join(species_info_entry(i) + "\n" for i in range(n))
    write_if_changed(os.path.join(OUT_DIR, "reserved_species_info.inc"), banner + body)

    # level_up_learnset_pointers.h
    lines = [f"    [{species_id(i)}] = sReservedSpeciesEmptyLearnset,\n" for i in range(n)]
    write_if_changed(os.path.join(OUT_DIR, "reserved_learnset_ptrs.inc"), banner + "".join(lines))

    # tmhm
    lines = [f"    [{species_id(i)}]    = TMHM_LEARNSET(0),\n" for i in range(n)]
    write_if_changed(os.path.join(OUT_DIR, "reserved_tmhm.inc"), banner + "".join(lines))

    # tutor
    lines = [f"    [{species_id(i)}] = 0,\n" for i in range(n)]
    write_if_changed(os.path.join(OUT_DIR, "reserved_tutor.inc"), banner + "".join(lines))

    # cry_ids.h — index is species - HOENN_MON_SPECIES_START (277)
    lines = [
        f"    [{species_id(i)} - HOENN_MON_SPECIES_START] = CRY_CHIMECHO,\n" for i in range(n)
    ]
    write_if_changed(os.path.join(OUT_DIR, "reserved_cry_ids.inc"), banner + "".join(lines))

    # graphics (manual designated initializers; not SPECIES_SPRITE macro)
    pic = []
    for i in range(n):
        sid = species_id(i)
        pic.append(
            f"    [{sid}] = {{gMonFrontPic_CircledQuestionMark, 0x800, {sid}}},\n"
        )
    write_if_changed(os.path.join(OUT_DIR, "reserved_front_pic.inc"), banner + "".join(pic))

    picb = []
    for i in range(n):
        sid = species_id(i)
        picb.append(
            f"    [{sid}] = {{gMonFrontPic_CircledQuestionMark, 0x800, {sid}}},\n"
        )
    write_if_changed(os.path.join(OUT_DIR, "reserved_back_pic.inc"), banner + "".join(picb))

    pal = []
    for i in range(n):
        sid = species_id(i)
        pal.append(f"    [{sid}] = {{gMonPalette_CircledQuestionMark, {sid}}},\n")
    write_if_changed(os.path.join(OUT_DIR, "reserved_palette.inc"), banner + "".join(pal))

    sh = []
    for i in range(n):
        sid = species_id(i)
        sh.append(
            f"    [{sid}] = {{gMonShinyPalette_CircledQuestionMark, {sid} + SPECIES_SHINY_TAG}},\n"
        )
    write_if_changed(os.path.join(OUT_DIR, "reserved_shiny_palette.inc"), banner + "".join(sh))

    fp = []
    for i in range(n):
        sid = species_id(i)
        fp.append(f"    [{sid}] = gMonFootprint_Bulbasaur,\n")
    write_if_changed(os.path.join(OUT_DIR, "reserved_footprint.inc"), banner + "".join(fp))

    coord = """        .size = MON_COORDS_SIZE(32, 32),
        .y_offset = 16,
"""
    fc = []
    for i in range(n):
        sid = species_id(i)
        fc.append(f"    [{sid}] =\n    {{\n{coord}    }},\n")
    write_if_changed(os.path.join(OUT_DIR, "reserved_front_coords.inc"), banner + "".join(fc))

    write_if_changed(os.path.join(OUT_DIR, "reserved_back_coords.inc"), banner + "".join(fc))

    # species names — short distinct labels for debugging
    nm = []
    for i in range(n):
        sid = species_id(i)
        nm.append(f'    [{sid}] = _("RSV{i:02d}"),\n')
    write_if_changed(os.path.join(OUT_DIR, "reserved_species_names.inc"), banner + "".join(nm))

    # pokemon.c dex tables (species-1 index)
    dex_h = []
    dex_n = []
    for i in range(n):
        sid = species_id(i)
        dex_h.append(f"    [{sid} - 1] = HOENN_DEX_NONE,\n")
        dex_n.append(f"    [{sid} - 1] = NATIONAL_DEX_NONE,\n")
    write_if_changed(os.path.join(OUT_DIR, "reserved_pokedex_hoenn.inc"), banner + "".join(dex_h))
    write_if_changed(os.path.join(OUT_DIR, "reserved_pokedex_national.inc"), banner + "".join(dex_n))


if __name__ == "__main__":
    main()
